import Config

# All worktrees of this repository share the main checkout's dev state:
# the database, the uploads folder, and the .env (see runtime.exs). From
# any linked worktree, `--git-common-dir` points into the main checkout's
# .git directory. Without git (or outside a repository), everything stays
# in this checkout.
shared_root =
  try do
    {git_common_dir, 0} =
      System.cmd("git", ["rev-parse", "--path-format=absolute", "--git-common-dir"],
        stderr_to_stdout: true
      )

    git_common_dir |> String.trim() |> Path.dirname()
  rescue
    _ -> Path.expand("..", __DIR__)
  end

# The people who may sign in. Every name here becomes an account at its
# first sign-in, with the password it chooses there. ADMIN_USERS in .env
# wins over this default, and in production it is the only source.
config :texttile, :admin_users, ["admin"]

config :texttile, Texttile.Repo,
  database: Path.join(shared_root, "texttile_dev.db"),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :texttile, TexttileWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # 4000 is the user's port (make start); agents pass PORT=4441+ (see AGENTS.md).
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "xnA6S8sQuhWpUgn1CDlEc8k8V4yN3V49kvRJD2q0L6D6ts3HKOj3C7Sny9XzGUzl",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:texttile, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:texttile, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :texttile, TexttileWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/texttile_web/router\.ex$"E,
      ~r"lib/texttile_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :texttile, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Uploaded files land in the main checkout, shared by every worktree
# like the database above.
config :texttile, :uploads_path, Path.join(shared_root, "priv/uploads")
