defmodule TexttileWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :texttile

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_texttile_key",
    signing_salt: "JrIhPccT",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Lets browser-driven tests share the test process's DB transaction.
  if sandbox = Application.compile_env(:texttile, :sql_sandbox) do
    plug Phoenix.Ecto.SQL.Sandbox, sandbox: sandbox
  end

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :texttile,
    gzip: not code_reloading?,
    only: TexttileWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :texttile
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # The session stands before the parser, so the body roof can ask who
  # is knocking. It reads no body of its own. Everything that does -
  # the method override reads `_method` out of the form - stays behind
  # the parser, where it was.
  plug Plug.Session, @session_options

  # Multipart carries the pictures and the videos; both are far past
  # Plug's 8 MB default. Two roofs, because they guard different
  # things.
  #
  # The small one is for everybody and never moves: 52 MB, which holds
  # a large photograph and the form around it. It is a guard, not a
  # setting, so nothing an admin types can raise it.
  #
  # The big one is Settings > Storage > Biggest upload, plus the form
  # around the file. It needs a signed-in session, not merely the right
  # address: the parser runs before the router, so without that check a
  # stranger could push half a gigabyte at the server and only be
  # turned away once it had all arrived. The cookie is signed, so the
  # token cannot be invented; whether it still names a live session is
  # the router's question, one roof later.
  #
  # The setting is read per upload, not at compile time, so a new limit
  # holds from the moment it is saved. Only the two upload addresses
  # ever ask, so no other request pays for the read.
  @picture_roof Plug.Parsers.init(
                  parsers: [:urlencoded, {:multipart, length: 52_000_000}, :json],
                  pass: ["*/*"],
                  json_decoder: Phoenix.json_library()
                )

  @form_around_the_file 2_000_000

  plug :parse_body

  defp parse_body(conn, _opts) do
    conn = fetch_session(conn)
    Plug.Parsers.call(conn, if(big_upload?(conn), do: admin_roof(), else: @picture_roof))
  end

  defp admin_roof do
    Plug.Parsers.init(
      parsers: [
        :urlencoded,
        {:multipart, length: Texttile.Settings.max_upload_bytes() + @form_around_the_file},
        :json
      ],
      pass: ["*/*"],
      json_decoder: Phoenix.json_library()
    )
  end

  defp big_upload?(conn) do
    upload_address?(conn.path_info) and signed_in?(conn)
  end

  # Both places a session token can arrive. A browser that was closed
  # and opened again carries only the auth cookie, and its first
  # request may well be the upload a restored tab was still holding:
  # reading the session alone would hand that one the small roof.
  defp signed_in?(conn) do
    is_binary(get_session(conn, :user_token)) or is_binary(auth_cookie_token(conn))
  end

  defp auth_cookie_token(conn) do
    name = TexttileWeb.UserAuth.auth_cookie()
    conn |> fetch_cookies(signed: [name]) |> Map.fetch!(:cookies) |> Map.get(name)
  end

  defp upload_address?(["admin", "texts", _id, "images"]), do: true
  defp upload_address?(["admin", "texts", _id, "gallery"]), do: true
  defp upload_address?(_path), do: false

  plug Plug.MethodOverride
  plug Plug.Head
  plug TexttileWeb.Router
end
