defmodule TexttileWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :texttile

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_texttile_key",
    signing_salt: "JrIhPccT",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Lets browser-driven tests share the test process's DB transaction.
  if sandbox = Application.compile_env(:texttile, :sql_sandbox) do
    plug Phoenix.Ecto.SQL.Sandbox, sandbox: sandbox
  end

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :texttile,
    gzip: not code_reloading?,
    only: TexttileWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :texttile
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Multipart carries the pictures and the videos; both are far past
  # Plug's 8 MB default. Two roofs, because they guard different
  # things: 52 MB everywhere, which holds a 50 MB photograph and the
  # form around it, and 520 MB on the two upload addresses of the desk,
  # which hold a 500 MB video (MAX_VIDEO_MB in gallery_core.js). A
  # public form never gets the big roof. Plug streams an upload to
  # disk, so a big one costs the volume, not the memory.
  @picture_roof Plug.Parsers.init(
                  parsers: [:urlencoded, {:multipart, length: 52_000_000}, :json],
                  pass: ["*/*"],
                  json_decoder: Phoenix.json_library()
                )

  @video_roof Plug.Parsers.init(
                parsers: [:urlencoded, {:multipart, length: 520_000_000}, :json],
                pass: ["*/*"],
                json_decoder: Phoenix.json_library()
              )

  plug :parse_body

  defp parse_body(conn, _opts) do
    Plug.Parsers.call(
      conn,
      if(upload_address?(conn.path_info), do: @video_roof, else: @picture_roof)
    )
  end

  defp upload_address?(["admin", "images"]), do: true
  defp upload_address?(["admin", "texts", _id, "gallery"]), do: true
  defp upload_address?(_path), do: false

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug TexttileWeb.Router
end
